name: Release Android App

on:
  push:
    branches:
      - development

jobs:
  build-and-release:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Archive APK
        run: mkdir -p ./build/apk && cp ./app/build/outputs/apk/release/*.apk ./build/apk/

      - name: Set APK path
        id: apk_path
        run: echo "APK_PATH=$(find ./build/apk -name '*.apk')" >> $GITHUB_ENV

      - name: Get version from Gradle
        run: echo "VERSION_NAME=$(./gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_NAME }}
          release_name: Release ${{ env.VERSION_NAME }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APK_PATH }}
          asset_name: simple-keyboard.apk
          asset_content_type: application/vnd.android.package-archive
